typography_spectrum: 0.29154
color:
  brandColors:
    - '#000000'
    - '#ea8a12'
    - '#734f1d'
    - '#ac671f'
    - '#40301b'
  brandStrength: 0.23134167515672743
  lightness: 0.30019882367923856
  saturation: 0.3661560630425811
  rhythmicContrast: 0.7408693199977279
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.49833
analytics:
  google: null
  facebook: null
  twitter: null
name: suninvestside
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Who are we?
    id: 3d119fd0-5e29-4b43-a741-54887c17c2ff
    type: content
  - name: About Side
    id: 4b6c7588-4fe0-4e52-953d-bf9595c70b4a
    type: content
  - name: Apartments
    id: 79f34846-d120-4f99-a0b1-33bb7a907ae6
    type: content
  - name: Elysium apartments & villa's
    id: 9b3a097a-e82b-49e2-8a04-0292e685021c
    type: content
favicon: null
title: 'Your real estate partner in the region of Side, Turkey.'
description: '#Side #Turkey #SecondHome'
purpose: []
